// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABpacSUMLEBxD6F_S1sPfkPadbcBrhRDI',
    appId: '1:646580884446:web:f593935634afee222d034f',
    messagingSenderId: '646580884446',
    projectId: 'phone-diagnostic-b9854',
    authDomain: 'phone-diagnostic-b9854.firebaseapp.com',
    storageBucket: 'phone-diagnostic-b9854.firebasestorage.app',
    measurementId: 'G-ZMEMTE4E78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Mw4LPWsPQp0hYgEj_YhJwQ5DtdynhiA',
    appId: '1:646580884446:android:9bfd8fb9fbc45fa42d034f',
    messagingSenderId: '646580884446',
    projectId: 'phone-diagnostic-b9854',
    storageBucket: 'phone-diagnostic-b9854.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH5gDGVpcjbri5dd2ao-X-KSqqjFjzB-8',
    appId: '1:646580884446:ios:91467975103508672d034f',
    messagingSenderId: '646580884446',
    projectId: 'phone-diagnostic-b9854',
    storageBucket: 'phone-diagnostic-b9854.firebasestorage.app',
    iosBundleId: 'com.miempresa.appsensores.flutterPrueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH5gDGVpcjbri5dd2ao-X-KSqqjFjzB-8',
    appId: '1:646580884446:ios:91467975103508672d034f',
    messagingSenderId: '646580884446',
    projectId: 'phone-diagnostic-b9854',
    storageBucket: 'phone-diagnostic-b9854.firebasestorage.app',
    iosBundleId: 'com.miempresa.appsensores.flutterPrueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABpacSUMLEBxD6F_S1sPfkPadbcBrhRDI',
    appId: '1:646580884446:web:61359b84ab5eb9cd2d034f',
    messagingSenderId: '646580884446',
    projectId: 'phone-diagnostic-b9854',
    authDomain: 'phone-diagnostic-b9854.firebaseapp.com',
    storageBucket: 'phone-diagnostic-b9854.firebasestorage.app',
    measurementId: 'G-4FL5XS3J47',
  );
}
